version: '3.7'
services:
  azure-cosmose-db-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    container_name: cosmosdb-emulator
    tty: true
    restart: always
    mem_limit: 1G
    cpu_count: 1
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
      - "8900:8900"
    volumes:
      - vol_cosmos:/data/db

volumes:
  vol_cosmos:
